Add QPG6105 IC
openthread/ot-qorvo pull request #178
Opened 2021-12-08 09:56 UTC by lucicop

Add support for new QPG6105 IC

2021-12-08 10:25 UTC, thcu-gp requested changes
Some reference to qpg6100 remaining

2021-12-08 10:25 UTC, thcu-gp commented on src/qpg6105/crypto/qpg6100-mbedtls-config.h
> +/*
Rename file, still named after qpg6100

2021-12-08 10:25 UTC, thcu-gp commented on third_party/Qorvo/CMakeLists.txt
>  # QPG6100 uses mbedtls_alt
update comment

2021-12-08 10:55 UTC, thcu-gp commented
@jwhui we're adding a new platform, can you review

2021-12-14 21:27 UTC, jwhui approved these changes
Thanks! 👍🏼

2021-12-14 21:27 UTC, merged